### PR TITLE
Add ontological model for urinary profiles

### PR DESCRIPTION
**Pull request by mozzherina**

### CODE REVIEW

**Comment by mozzherina** [comment]
In "moura2021well" the 4th original diagram contains "complex event" and "disposition" stereotypes. The question is whether this diagram should be reproduced.

**Comment by claudenirmf** [comment]
> In "moura2021well" the 4th original diagram contains "complex event" and "disposition" stereotypes. The question is whether this diagram should be reproduced.

Yes, that's some very important information to us. We want to know what stereotypes people are making use of that currently are not part of OntoUML. You can use [this tutorial](https://www.visual-paradigm.com/support/documents/vpuserguide/1283/177_usingstereot.html) to learn how to add stereotypes in Visual Paradigm, so you can represent these cases.

Screen Shot 2021-12-16 at 13 12 45

Notice that the labels in the top right corner of classes (e.g., `Person`, `Operator`, and `MLSchema::Data`) are shortcuts for respresenting specializations in a tool called Enterprise Architect (example [here](https://youtu.be/Iw3FjQ-qxt8?t=1640)). You should represent this information by adding the class and the specialization to your model. For exemple, you should add `Person` to the model and create a generalization between it and `User`.

Notice that you are not creating new branches for each model you introduce, so all your contributions become part of the same pull request. Please let us know when you have "finnished" so we can review them.

**Comment by mozzherina** [comment]
> > In "moura2021well" the 4th original diagram contains "complex event" and "disposition" stereotypes. The question is whether this diagram should be reproduced.
> 
> Yes, that's some very important information to us. We want to know what stereotypes people are making use of that currently are not part of OntoUML. You can use [this tutorial](https://www.visual-paradigm.com/support/documents/vpuserguide/1283/177_usingstereot.html) to learn how to add stereotypes in Visual Paradigm, so you can represent these cases.

Ok, I'll add stereotypes

> Notice that the labels in the top right corner of classes (e.g., `Person`, `Operator`, and `MLSchema::Data`) are shortcuts for respresenting specializations in a tool called Enterprise Architect (example [here](https://youtu.be/Iw3FjQ-qxt8?t=1640)). You should represent this information by adding the class and the specialization to your model. For exemple, you should add `Person` to the model and create a generalization between it and `User`.

Ok, got it

> Notice that you are not creating new branches for each model you introduce, so all your contributions become part of the same pull request. Please let us know when you have "finnished" so we can review them.

Ahhh... I forgot to create new branches!! Ok, let's left this branch for 'rodrigues2017ontological' only. Everything else I'll put into other branches. Thank you.

**Comment by mozzherina** [comment]
Ok, _rodrigues2017ontological_ could be reviewed. Thank you.

**Comment by claudenirmf** [comment]
The issue is that I cannot review them independently because they are all in a single pull request. We the pull request is eventually accepted, all of them will accepted at once. To make independent/parallel pull requests you need to create a new branch for each ontology you want to document.

Since I cannot produce any resources on how to work with branches at the moment, you can continue with your work until you learn that. When I started using git, I read this [article](https://nvie.com/posts/a-successful-git-branching-model/) and it was very helpful to me. Maybe this could clarify these ideas for you as well.

**Pull request closed without merging**
