### PR TITLE
Predictive System for University Admissions "UniMatch" 

### PR DESCRIPTION
**Pull request by antialman**
Ontology created for the course "Information System Design Course" at the Free University of Bozen-Bolzano.

### CODE REVIEW

**Review by pedropaulofb — APPROVED** [review]
Thank you very much for your contribution, @antialman and @arasherami ! I noticed you sent the model without an authorship. Please send me a message if you want me to attribute the model to you in the future. Kind regards.

**Comment by antialman** [comment]
I am ok with being listed as one of the authors, but I am not sure if others prefer to remain anonymous.

**Comment by arasherami** [comment]
Hi
Yes, that would be great.
I will be happy to put my name.

Best regards

**Comment by pedropaulofb** [comment]
In this case, please send me one URI for each author of the paper. We prefer the DBLP URI. You can find more instructions here: https://github.com/unibz-core/ontouml-models/wiki/How-to-Contribute#the-ontology-metadata-file (check the item "contributor")

**Comment by antialman** [comment]
Mine is https://dblp.uni-trier.de/pid/273/7024.html

**Comment by arasherami** [comment]
I had ORICID already.
Is this ok?

https://orcid.org/0000-0001-5500-6301

**Comment by antialman** [comment]
Just in case, my ORICID is: https://orcid.org/0000-0002-5647-6249

**Comment by pedropaulofb** [comment]
@antialman and @arasherami , thank you for the ORCIDs. They are fine for us.

Are there other authors to add to the contributors list?

**Comment by antialman** [comment]
There are two more authors, I will ask them.

**Comment by antialman** [comment]
@pedropaulofb The ORCIDs of the other two authors are:
* https://orcid.org/0000-0002-4278-3782
* https://orcid.org/0000-0001-9993-4484

**Comment by antialman** [comment]
Yes, https://orcid.org/0000-0002-4278-3782 is the same person as https://dblp.org/pid/258/0384.html

**Comment by pedropaulofb** [comment]
Done! Once again, thank you very much for the contribution!

Kind regards - Cordiali saluti - Atenciosamente,
Pedro Paulo Favato Barcelos


Em qua., 1 de fev. de 2023 às 19:48, Anti Alman ***@***.***>
escreveu:

**Comment by arasherami** [comment]
Perfect.
Thank you

**Comment by antialman** [comment]
Thank you from my side as well!

**Pull request merged**
