### PR TITLE
Added a new ontology, SDP-Ontology

### PR DESCRIPTION
**Pull request by marcj97**

### CODE REVIEW

**Comment by pedropaulofb** [comment]
Thank you very much for your contribution to the catalog, @marcj97! I'll process your PR still during this week.

**Comment by pedropaulofb** [comment]
@marcj97 , I have reviewed your PR. Some modifications were necessary and I have already made them. Can you please review my last commit and give me your OK for merging the PR into the master branch? Please note that I added the https://creativecommons.org/licenses/by/4.0 license. If you want another license for your work, please make the modification. Thank you very much in advance.

**Comment by marcj97** [comment]
Thank you for making the modifications, hereby my OK for the merge

**Review by pedropaulofb — APPROVED** [review]
Dataset was reviewed and approved.

**Comment by pedropaulofb** [comment]
PR merged into the master branch. @marcj97, your model was added with the name jacobs2022sdpontology. Once again, thank you very much for your contribution. We kindly ask you to please continue to do that with the new models you're building. Please let us know if there is something we can help you with.

**Pull request merged**
