### PR TITLE
OntoRights in two versions: Full and Simple

### PR DESCRIPTION
**Pull request by JoranL**
I am a beginner with GitHub, I hope I have done this right. 

I know the instructions states only inlcude one ontology in each pull request, but I thought this could be an exception since they are two versions. Simple OntoRights was derived from Full OntoRights.

### CODE REVIEW

**Comment by pedropaulofb** [comment]
Hi @JoranL, thank you for your contribution. 

The instructions indicate that only the most updated version of the ontology (e.g., v1.1 instead of v1.0) is going to be included into the catalog. In your case, seems that the ontologies sent have different scope and requirements and, hence, probably they are eligible to be both included in the catalog (in this case I am going to spit them in two different datasets (i.e., folders)). 

I am going to analyze the data you sent up to the end of the next week, ok?

Once again, thank you very much!

**Comment by JoranL** [comment]
Hello @pedropaulofb,

Yes, they have a different scope as you said. 

Thank you for reviewing!
Jöran

**Comment by pedropaulofb** [comment]
@JoranL, can you please answer the two following questions so I can finalize the ontologies' inclusion on the OntoUML/UFO Catalog?

1) Were the ontologies originally created using the OntoUML-VP Plugin at the Visual Paradigm?
2) Are there any published works about the ontologies?

Kind regards.

**Comment by pedropaulofb** [comment]
@JoranL, I've made a modification to the datasets (folders) you provided. Can you please validate them before I approve the inclusion of the ontologies into the catalog?

1) I made a minor correction on the metadata.yaml file (editorialNote field) so it can be totally compatible with the yaml syntax.
2) Still in the metadata.yaml file, I included your thesis in the source field.
3) I created the references.bib files for both folders.

Thank you in advance.

**Comment by JoranL** [comment]
@pedropaulofb, thank you for the corrections! 

I have looked at the corrections and all looks good. (Please let me know if there is a button I should click to validate technically)

Yes, both ontologies were originally created using the OntoUML-VP Plugin.

No, apart from my master thesis there are still no published works about the ontologies. 

Best regards, 
Jöran

**Review by pedropaulofb — APPROVED** [review]

**Comment by pedropaulofb** [comment]
Two new datasets included into the catalog.

**Comment by pedropaulofb** [comment]
Thank you very much @JoranL for contributing to the whole OntoUML/UFO community! I'm concluding this PR. Both works were included in the catalog.

**Pull request merged**
