### PR TITLE
Add the Design Science Artifact Ontology

### PR DESCRIPTION
**Pull request by tgoprince**

### CODE REVIEW

**Review by claudenirmf — CHANGES_REQUESTED** [review]
@tgoprince, did you take the opportunity to update the `vpp` file of `neves2021ontology` as well?

I'm fine with minor corrections like this, but then we need to update the JSON export as well.

Otherwise, I'm happy to approve and merge the PR.

**Comment by claudenirmf** [comment]
If you want to check the history, `neves2021ontology` has been added in #3 but there was a confusinfg revert involved.

**Comment by tgoprince** [comment]
> @tgoprince, did you take the opportunity to update the `vpp` file of `neves2021ontology` as well?

That was not on purpose. I'll revert that file.

**Comment by tgoprince** [comment]
I actually undid the original commit, removed the neves vpp file and recommitted the changes again while keeping all your improvements in this submission.

I think this is ready to be merged now.

**Pull request merged**
