### PR TITLE
ANTT Ontology Completed

### PR DESCRIPTION
**Pull request by pedropaulofb**

### CODE REVIEW

**Comment by tgoprince** [comment]
Can we add the original diagrams to this submission?

**Comment by claudenirmf** [comment]
The Portuguese text in the `ontology.json` seems to be enconded in `Windows 1252`. I'll look into how to export that properly.

**Comment by pedropaulofb** [comment]
I'm going to work on the issues here reported in a few hours. I'll create the references.bib file and also I'll try to generate the original diagrams. Please wait up to 12h CET at most.

**Comment by claudenirmf** [comment]
@Matt-81, could you please test the `ontology.json` file with your code? It should be fine now

**Comment by pedropaulofb** [comment]
The original diagrams were created, however, I couldn't automate the creation of the files' names. The manual creation is going to take a long time... does someone know how can we do that?

**Comment by tgoprince** [comment]
I reduced the size of new diagrams in about 60% using https://tinypng.com

**Comment by tgoprince** [comment]
> The original diagrams were created, however, I couldn't automate the creation of the files' names. The manual creation is going to take a long time... does someone know how can we do that?

How do you expect to automate this and why doesn't EA export diagrams with their correct names?

**Comment by tgoprince** [comment]
I reduced the size of new diagrams in about 60% using PNG compression services.

**Comment by pedropaulofb** [comment]
> > The original diagrams were created, however, I couldn't automate the creation of the files' names. The manual creation is going to take a long time... does someone know how can we do that?
> 
> How do you expect to automate this and why doesn't EA export diagrams with their correct names?

I couldn't find any EA feature to export all diagrams in png format, only individual ones. So I created a PDF report with all diagrams and then transformed them to images.

**Comment by Matt-81** [comment]
@claudenirmf Tested, it works and all the associations are present!

**Review by claudenirmf — APPROVED** [review]

**Review by Matt-81 — APPROVED** [review]

**Pull request merged**
