### PR TITLE
Add sustainability ontology

### PR DESCRIPTION
**Pull request by cgtsbr**
Hi.
I share my ontology to participate in the OntoUML dataset hackathon.

### CODE REVIEW

**Review by Matt-81 — COMMENTED** [review]
Dear Cristiano, thanks for your contribution.
Here is some feedback for updating your submission:

**Comment by Matt-81** [comment]
Please,
1. delete the following files from the repository: SEBIM.oled, SEBIM_gUFO.owl
2. add the following folders "original diagrams" and "new diagrams". Paste the screenshots of the original diagrams from the paper in the former. Paste the screenshots from your new diagram in the latter
3. add the metadata.yaml file and compile it as from the guidelines
4. please check the guidelines here https://github.com/unibz-core/ontouml-models/wiki/How-to-Contribute and here https://github.com/unibz-core/ontouml-models/wiki/Frequently-Asked-Questions to address the above points

**Review by Matt-81 — CHANGES_REQUESTED** [review]
see my previous comments

**Comment by cgtsbr** [comment]
Okay. I performed the updates. Thanks

**Comment by Matt-81** [comment]
Great, thanks, Cristiano!

**Comment by Matt-81** [comment]
Sorry, Cristiano, can you make your pull request again? I am going to merge it asap! thx

**Comment by Matt-81** [comment]
Great, thanks, Cristiano!

**Pull request merged**
